import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.sass';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Akikun no Outa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p className="text-2xl">
          This is an example project of Next.js.
        </p>
      </main>
    </div>
  );
}

export default Home
